services:
   db:
    image: postgres:16
    container_name: 'db'
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DATA_BASE_PORT}:${DATA_BASE_PORT}"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
    

   app:
    image: nikitaburak/myapp-musik:tagname
    tty: true
    stdin_open: true
    container_name: 'app'
    ports:
      - '$PORT:$PORT'
      - '$STUDIO_PRISMA_PORT:$STUDIO_PRISMA_PORT'
    depends_on:
      - db
    restart: on-failure
    
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - internal



volumes:
     db_data:
    
networks:
  internal:
    driver: bridge
    name: 'internal'

