services:
   db:
    image: postgres
    container_name: 'db'
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DATA_BASE_PORT}:${DATA_BASE_PORT}"
    env_file:
      - .env
    

   app:
    build: .
    container_name: 'app'
    ports:
      - '$PORT:$PORT'
      - '$STUDIO_PRISMA_PORT:$STUDIO_PRISMA_PORT'
    depends_on:
      - db
    restart: always
    
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    

